#define WINDOW_WIDTH 1024 
#define WINDOW_HEIGHT 768

#define NUMSTARS 200
//#define MAXNUMENEMIES 500
//#define MAXNUMHEALTHAMMO 5
#define MAXNUMLASERS 20
#define MAXNUMEXPLOSIONS 20

// #define MAIN_VIEWPORT_X 763
// #define MAIN_VIEWPORT_Y 5
// #define MAIN_VIEWPORT_WIDTH 261
// #define MAIN_VIEWPORT_HEIGHT 758

#define MAIN_VIEWPORT_X 5
#define MAIN_VIEWPORT_Y 5
#define MAIN_VIEWPORT_WIDTH 758
#define MAIN_VIEWPORT_HEIGHT 758

#define DATA_VIEWPORT_X 768
#define DATA_VIEWPORT_Y 5
#define DATA_VIEWPORT_WIDTH 251
#define DATA_VIEWPORT_HEIGHT 758

#define VIEWPORT_BUFFER 50
#define VIEWPORT_SHIFT_SPEED .05f
#define VIEWPORT_PADDING 20

//Ship Boundries
// #define MINX_PLAYABLE_AREA 20
// #define MAXX_PLAYABLE_AREA 620
// #define MINY_PLAYABLE_AREA 20
// #define MAXY_PLAYABLE_AREA 460

#define SHIPREST 380
#define NUDGEAMOUNT 1

//#define MINX_PLAYABLE_AREA 10
//#define SHIP_VEL_INCREMENT_F 1.8
#define SHIP_VEL_DECAY 0.995f
#define SHIP_TURN_DECAY 0.75f
#define SHIP_IMPULSE_F 1.8f
#define SHIP_IMPULSE_B 0.8f
#define SHIP_IMPULSE_L 0.75f
#define SHIP_IMPULSE_R 0.75f
#define SHIP_IMPULSE_A 0.12f

#define SHIP_MAX_VEL 30
#define SHIP_MAX_TURN_VEL .15f

#define SHIP_START_X 450;
#define SHIP_START_Y -300;


#define MINVELX -2
#define MAXVELX 2
#define MINVELY .5
#define MAXVELY 2.5

#define STARVELRATIO .3
#define MINSTARVEL .5
#define MAXSTARVEL 3

// #define LASERVEL 8
// #define LASERVELENEMY 5
// #define LASERVELXDAMPING .7

// #define LASERCOLOR_R 0
// #define LASERCOLOR_G 255
// #define LASERCOLOR_B 0

// #define LASERCOLOR_ENEMY_R 255
// #define LASERCOLOR_ENEMY_G 0
// #define LASERCOLOR_ENEMY_B 0

// #define COLDISTANCEX 10
// #define COLDISTANCEY 10
// #define COLDISTANCEXHEALTH 15
// #define COLDISTANCEYHEALTH 15

// #define EXPLOSIONSIZE 20
// #define EXPLOSIONPARTICLES 10
// #define EXPLOSIONSPREAD 15

// #define HEALTHAMMOCHANCE 2500
// #define ENEMYFIRECHANCE 250
// #define AMMOCHANCE 200
// #define HEALTHCHANCE 500

// #define HEALTHDECREASEINCREMENT 10

#define frameDelay 16.6667
#define DEFFONTSIZE 16
#define TWOPIRAD 6.283185


