#define WINDOW_WIDTH 1024 
#define WINDOW_HEIGHT 768

#define NUM_STARS 200

#define MAX_FILE_LEN 24

#define MAX_NUM_ENEMIES 50
#define MAX_NUM_LASERS 20
#define MAX_NUM_EXPLOSIONS 20
#define NUM_EXPLOSIONS 5

#define MAIN_VIEWPORT_X 5
#define MAIN_VIEWPORT_Y 5
#define MAIN_VIEWPORT_WIDTH 758
#define MAIN_VIEWPORT_HEIGHT 758
#define MAIN_VIEWPORT_MAX_SCALE 2
#define MAIN_VIEWPORT_MIN_SCALE 0.75f

#define DATA_VIEWPORT_X 768
#define DATA_VIEWPORT_Y 5
#define DATA_VIEWPORT_WIDTH 251
#define DATA_VIEWPORT_HEIGHT 758

#define VIEWPORT_BUFFER 50
#define VIEWPORT_SHIFT_SPEED .05f
#define VIEWPORT_PADDING 20

#define SHIPREST 380
#define NUDGEAMOUNT 1

#define SHIP_VEL_DECAY 0.997f
#define SHIP_TURN_DECAY 0.9f
#define SHIP_IMPULSE_F .08f
#define SHIP_IMPULSE_B 0.04f
#define SHIP_IMPULSE_L 0.2f
#define SHIP_IMPULSE_R 0.2f
#define SHIP_IMPULSE_A .5

#define SHIP_MAX_VEL 10
#define SHIP_MAX_TURN_VEL 4

#define SHIP_START_X 0;
#define SHIP_START_Y 0;

#define MINVELX -2
#define MAXVELX 2
#define MINVELY .5
#define MAXVELY 2.5

#define STARVELRATIO .3
#define MINSTARVEL .5
#define MAXSTARVEL 3

#define LASER_VEL 7
#define LASER_LEN 20
#define LASER_BUFFER 20
#define LASER_LIFE 200

#define MAX_CALLSIGN_LEN 16
#define FRAME_PADDING 22

#define frameDelay 16.66667f
#define DEF_FONT_SIZE 16
#define RAD_TO_DEG 0.017453f
#define DEG_TO_RAD 57.29583f
#define PI 3.14159f


